### ISSUE TITLE
latest diff and question

### ISSUE THREAD

**Issue by phit** [intrnl/discord-diff#1]
Heyo, thank you for this!
Any plans to make the script to create those diffs also open source? The situation right now is, Discord broke some stuff again by moving the guild bar to their obfuscated names. And would be nice if we could create those ourselves, instead of having to wait.

Or is this still a lot of manual work?

**Comment by intrnl** [comment]
It's manual work, I haven't had much time to do things for the past several weeks and probably won't be for a while. The diff files are based off the commits in [fluffingtons/discord-css](https://github.com/fluffingtons/discord-css/commits) repository.

I can't really put out diff files for changes from non-obfuscated to obfuscated ones, I'm afraid that there would be conflicts with how some elements having the same class name but are drastically different in terms of how they look.

**Comment by phit** [comment]
makes sense and thanks for that repo link that already helps a lot!
